### PR TITLE
Clearly distinguish between relative and absolute paths in config

### PR DESCRIPTION
**Pull request by jherbel**

### CODE REVIEW

**Comment by jherbel** [comment]
@SoloJacobs Not 100% sure about this, what is your opinion?

**Comment by SoloJacobs** [comment]
I'm not sure. Building type safe abstractions over the filesystem seems a bit overkill for what we are doing.

We also have some other areas, which are more in need of attention.

Maybe ask Mathias? He is part of the elabit organization, and thus can review here on GH.

**Comment by jherbel** [comment]
@Synss We are unsure whether this is overengineering. What is your opinion on this? We don't need a detailed review of course. Feel free to ping us for discussions.

**Comment by Synss** [comment]
I agree with Solomon. I don't see how distinguishing between absolute and relative paths is relevant. If anything, it will make the code harder to test.

**Comment by jherbel** [comment]
Ok, thanks for the feedback, then I'll close this PR.

**Pull request closed without merging**
