### PR TITLE
rmk: Adjust scheduler for core mode (no-op)

### PR DESCRIPTION
**Pull request by racicLuka**
`RCCProfileConfig` is now optional. If the value is `None`, skip RCC profile configuration.

### CODE REVIEW

**Comment by SoloJacobs** [comment]
I don't think this quite correct: `rcc_setup` and `setup` are still doing a lot of  setup. I think you should modify `src/bin/scheduler/rcc.rs` to not do any configuration of rcc and only return surviving_suites.

**Review by SoloJacobs — CHANGES_REQUESTED** [review]
Please modify `setup` in src/bin/scheduler/setup/rcc.rs instead of `configure_curstom_rcc_profile`.

**Comment by racicLuka** [comment]
So something like:
```
if global_config.rcc_config.profile_config.is_none() {
        sort_suites_by_grouping(&mut surviving_suites);
        Ok(surviving_suites);
    }
```
on line https://github.com/elabit/robotmk/blob/7f671ceec0965350b7be8a031356d7de15e27740/src/bin/scheduler/setup/rcc.rs#L26?

**Comment by SoloJacobs** [comment]
Yes, but you can use pattern matching to unwrap  the profile and then it can be used in the body of the function. The rust tooling should be able to help you with this.

Also add some logging why that rcc configuration is skipped would be good.

In the end, I will write an integration test to check that rcc is never called.

**Comment by racicLuka** [comment]
Sorry for the late response, I wasn't feeling well. 
I tried what you proposed, using pattern matching, but I can't get it to work. I just can't wrap my head around some concepts in Rust :/ 
If you have time, I would appreciate if we could take a look together. Thanks! 

PS. At least this way the profile configuration is skipped. I tested it in a site.

**Review by SoloJacobs — APPROVED** [review]
LGTM, let's wait for the test before we release this.

**Review by SoloJacobs — APPROVED** [review]

**Pull request merged**
